### PR TITLE
sign up

### PR DESCRIPTION
**Pull request by john-lumi**

### CODE REVIEW

**Comment by john-lumi** [comment]
convert

**Comment by kofoworola01** [comment]
@jazzygee36 I can't access the signup page by clicking on the signup button. Kindly look into this

**Comment by kofoworola01** [comment]
The spacing between the label and the input field on the signup page is a bit small, please check the design
Also, the password has a toggle icon to view and hide passwords, this is not included in your work.

this is an image of yours vs design
Screenshot 2023-06-15 at 07 04 27
Screenshot 2023-06-15 at 07 07 48

**Comment by kofoworola01** [comment]
On the convert page, kindly look into the design of the form here, it's quite different.
Also, there is a tab on this page to switch between crypto and giftcard. Kindly implement this. Thank you 

an image of your work vs design 

Screenshot 2023-06-14 at 11 46 12
Screenshot 2023-06-14 at 11 46 17

**Review by kofoworola01 — APPROVED** [review]

**Pull request merged**
